spring:
  profiles:
    active: rest
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

---
spring:
  profiles: security
db:
  dialect: org.hibernate.dialect.MySQL8Dialect
  dbop: create
  url: jdbc:mysql://localhost:3306/security
  username: root
  password: '9090'

---
spring:
  profiles: rest
db:
  dialect: org.hibernate.dialect.MySQL8Dialect
  dbop: create
  url: jdbc:mysql://localhost:3306/restapi
  username: root
  password: '9090'