security:
  dialect: org.hibernate.dialect.MySQL8Dialect
  dbop: create
  url: jdbc:mysql://localhost:3306/security
  username: root
  password: '9090'

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        cache: DEBUG
        stat: DEBUG